name: guia_reciclagem
description: "Um guia prático de reciclagem para a comunidade."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Atualizado para uma versão mais moderna do Dart

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/ 

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/eco.png"
  min_sdk_android: 21 # Importante para Androids mais novos